version: '3'

services:

  spring-boot-s8-app:
    container_name: s8bc-app
    build:
      context: .
      dockerfile: Dockerfile
    image: spring-boot-s8-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: '{"spring":{"datasource":{"url":"jdbc:mysql://mysqldb:3306/challenge","username":"root","password":"root"},"jpa":{"hibernate":{"ddl-auto":"create-drop"},"database-platform":"org.hibernate.dialect.MySQLDialect"},"kafka":{"bootstrap-servers":"kafka:9092"}}}'
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    depends_on:
      - mysqldb
      - kafka

  mysqldb:
    container_name: mysqldb
    image: mysql:8-oracle
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: challenge
      MYSQL_ROOT_PASSWORD: root

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    restart: on-failure
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_NUM_PARTITIONS: 12
    depends_on:
      - zookeeper
