version: '3'

services:

  spring-boot-s8-app:
    container_name: s8bc-app
    image: spring-boot-s8-app
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_PORT: 3306
    depends_on:
      - mysqldb
      - kafka

  mysqldb:
    container_name: mysqldb
    image: mysql:8-oracle
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: challenge
      MYSQL_ROOT_PASSWORD: root

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    restart: on-failure
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
