
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/challenge
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  kafka:
    bootstrap-servers: kafka:9092

logging:
  level:
    root: info
    com:
      s8:
        keeilzhanstd:
          challenge: debug

jwt:
  secret: 472D4B6150645367566B597033733676397924423F4528482B4D625165546857

fx:
  secret: 778d2472420ef861e2c96556