version: '2'
jobs:
  build:

    working_directory: ~/circleci-s8

    machine: true
    steps:
      - checkout
      - restore_cache:
          key: circleci-s8-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache: # saves the project dependencies
          paths:
            - ~/.m2
          key: circleci-s8-{{ checksum "pom.xml" }}

      - run: mvn clean
      - run: mvn package # run the actual tests

      - store_test_results: # uploads the test metadata from the `target/surefire-reports` directory so that it can show up in the CircleCI dashboard.
          path: target/surefire-reports