version: 2 # use CircleCI 2.0
orbs:
  maven: circleci/maven@1.4.0
  tcc: atomicjar/testcontainers-cloud-orb@x.y
workflows:
  build_and_test:
    jobs:
      - maven/test:
          command: verify
          executor: jdk17
          pre-steps:
            - tcc/setup